### ISSUE TITLE
 Line 65:26:  'Paragraph' is not defined  react/jsx-no-undef

### ISSUE THREAD

**Issue by SoftwareDev1014** [rsuite/rsuite#1088]

**Comment by TolrenFrank** [comment]
Line 65:26:  'Paragraph' is not defined  react/jsx-no-undef

**Comment by simonguo** [comment]
Please describe your problem in detail.

**Comment by eDubrovsky** [comment]
> Line 65:26: 'Paragraph' is not defined react/jsx-no-undef

I think you trying to import `Paragraph` from `rsuit`.

Do this:
`import { Placeholder } from 'rsuite'` 
and in your app use `<Placeholder.Paragraph/>`

**Comment by simonguo** [comment]
I cannot reproduce the issue.   What are the steps to reproduce?

**Comment by eDubrovsky** [comment]
@simonguo It's not issue in `rsuit`.

I think, @TolrenFrank copy any example from the doc (like `Panel`) and see code:
~~~~
const instance = (
  <Panel header="Panel title">
    <Paragraph />
  </Panel>
);
~~~~

If you a new user, you can be a little confused, because you don't know that `Paragraph` need be imported from `Placeholder` :)
