### ISSUE TITLE
Custom theme not working

### ISSUE THREAD

**Issue by Nick-kel** [rsuite/rsuite#1858]
### What version of rsuite are you using?
5.0.0-beta.1

### What version of React are you using?
17.0.2

### What browser are you using?
Chrome

### Describe the Bug
The custom theme in the config-overrides.js (e.g. the primary-color) is not working. It is still the default primary color.

### Expected Behavior
The modified vars in the config-overrides.js should be used.

### To Reproduce
config-overrides.js File: https://github.com/LupoBot/LupoWeb/blob/custom-theme/config-overrides.js
Commit: https://github.com/LupoBot/LupoWeb/commit/cd39f170e0fefc455cdbe832d2abec0d7eed6de7

**Comment by SevenOutman** [comment]
You are using compiled RSuite CSS but customizing Less variable only works when you are compiling the Less styles. 

https://github.com/LupoBot/LupoWeb/blob/custom-theme/src/index.js#L4

Change this line to

```js
import "rsuite/styles/index.less";
```

### But before your do so

You  need to upgrade to a newer beta version of RSuite because `5.0.0-beta.1` has other problems with Less styles itself.

**Comment by Nick-kel** [comment]
Thank you!
