### ISSUE TITLE
Table component in Tree/child mode - expanding row scrolls to top

### ISSUE THREAD

**Issue by thelazydogsback** [rsuite/rsuite#1948]
When using the Table component with child rows in **isTree** mode, when a row is expanded, the view will always scroll to the very top.

This can be repo'd in the example table in the rsuite docs here:
[https://rsuitejs.com/components/table/]  under the Tree section - simply scroll the bottom of the table, and then expand one of the nodes like Game or Digtal.

thanks

**Comment by thelazydogsback** [comment]
Setting **shouldUpdateScroll=false** solves this problem.  I'm not sure if this is intentional or not, because it doesn't seem like row expansion would could as a "data update" per the shouldUpdateScroll docs.

**Comment by simonguo** [comment]
The scroll bar of the Table will be recalculated every time the size of the content area changes. When the size changes, the position of the scroll bar will be reset. This can be due to a change in the data size or a change in the content style. So setting `shouldUpdateScroll=false` is the current solution.

**Comment by thelazydogsback** [comment]
Thanks for the explanation
