### ISSUE TITLE
"open" property of "Dropdown" has been deprecated. Still in Docs and no alternative

### ISSUE THREAD

**Issue by daffron** [rsuite/rsuite#2090]
### What version of rsuite are you using?

5.1.0

### What version of React are you using?

16.3.1

### What browser are you using?

Chrome

### Describe the Bug

The controlled state prop for `Dropdown` is showing a deprecation error in the console, however it is still listed as a prop in the documentation.

### Expected Behavior

`open` to still be valid prop, or an alternative.

Use case is externally controlled Dropdown from things like Redux

### To Reproduce

Simply use the dropdown, passing the open prop

```
<Dropdown open={ true } />
```

**Comment by daffron** [comment]
![image](https://user-images.githubusercontent.com/24515104/139750396-945a7b77-f6e2-4627-a084-46aba4893a9b.png)

**Comment by daffron** [comment]
![image](https://user-images.githubusercontent.com/24515104/139750455-a8142c87-9308-4723-a4c7-5881a9603427.png)

**Comment by SevenOutman** [comment]
Hi @daffron , `open` prop is deprecated because it conflicts with `<Sidenav>`'s controlled `openKeys` prop. There is no controlled open state on a `<Dropdown>` before we can separate `<Dropdown>` from usage inside `<Sidenav>`.

As as workaround for now, you may use `<Whisper>` for controlling show/hide elements manually. Here's a related example https://rsuitejs.com/components/popover/#used-with-dropdown

**Comment by SevenOutman** [comment]
We have removed the `open` prop from documentation now.
