### ISSUE TITLE
DatePicker should support yyyy format

### ISSUE THREAD

**Issue by MasanoriOnishi** [rsuite/rsuite#2305]
### What problem does this feature solve?
I want to use DatePicker also for only year input.
But now DatePicker does not support only yyyy format.(In the Screenshot, selecting part is white over...)

This feature solve such a problem.

<img width="520" alt="スクリーンショット 2022-01-15 5 41 08" src="https://user-images.githubusercontent.com/28590024/149582670-2f7c83b8-38ce-489f-ad76-85d2335565ab.png">
(↑from: https://rsuitejs.com/components/date-picker/#disabled-and-read-only)

This request does not seems odd, because DatePicker supports only HH format.
<img width="459" alt="スクリーンショット 2022-01-15 5 47 33" src="https://user-images.githubusercontent.com/28590024/149583063-756079da-3f5a-4545-af54-eee250e5a4f2.png">
(↑from: https://rsuitejs.com/components/date-picker/#disabled-and-read-only)

**Comment by SevenOutman** [comment]
Hi @MasanoriOnishi, selecting one year out of several does not require a calendar view, I think SelectPicker is suitable.

**Comment by SevenOutman** [comment]
Hi @MasanoriOnishi, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.

**Comment by zulianAdryan** [comment]
Hello, I know maybe it seems SelectPicker could answered this issue, but actually it needs to be available in years only format because in purpose of the similarity of date input. just imagine there is a row or column of date form it would be nice and user friendly if its in the same shape of DatePicker shape form so the user won't be confused and know that they are still in the same section on date form
