### ISSUE TITLE
DateRangePicker - shifted digits when using format={"M/d/yyyy"}

### ISSUE THREAD

**Issue by mtulodzi** [rsuite/rsuite#2575]
### What version of rsuite are you using?

5.15.2

### What version of React are you using?

16.8.6

### What version of TypeScript are you using (if any)?

4.7.4

### What browser are you using?

Edge

### Describe the Bug

The dates in textbox are shifted in edit mode, after playing with manual typing for format={"M/d/yyyy"}
Instead of "6/30/2022 - 7/6/2022" there is "6/3/0202 - 2/7/6202", but when I lose focus on control it is correct range.

### To Reproduce

https://codesandbox.io/s/rsuite-daterangepicker-issue-1-x44pj0?file=/src/index.js:390-409

Steps:
1. Click on control.
2. Select from 29th of July 2022 till 3rd of August 2022.
3. Click OK.
4. Click on control, change starting date using typing method in textbox to 28th of July 2022.
5. Digits are shifted.
6. Select from the calendar 27th of July 2022 till 3rd of August 2022.
7. Click OK.
8. Click on control, the text box is showing shifted digits 7/2/7202 - 2/8/3202.

**Comment by simonguo** [comment]
Hi @mtulodzi  
The input format in DateRangePicker uses [MaskedInput](https://rsuitejs.com/components/input/#masked-input). So that every character of the date input is restricted by the regular expression. So it is recommended that you change the `format` to `MM/dd/yyyy`.

**Comment by daggmano** [comment]
While that solves the issue from a technical point of view, it's not really an acceptable solution from a user perspective. For user friendliness we would prefer to use something like 'd MMM yyyy' (e.g. 8 Aug 2022), however this then breaks for dates later in the month (18 Aug 2022 becomes 1 8Au g202, which is pretty ugly).

In order to make this more customer-focused, could you please reconsider your response to this issue?

**Comment by mtulodzi** [comment]
In our app User is able to select how he want to have dates formatted.

To partially solve this issue, we are overriding User settings. Ex. from 'M/d/yyyy' to 'MM/dd/yyyy'.
