### ISSUE TITLE
Virtual table stutters in React 18

### ISSUE THREAD

**Issue by Zamaletdinov** [rsuite/rsuite#2809]
### What version of rsuite are you using?

^5.19.0

### What version of React are you using?

^18.2.0

### What version of TypeScript are you using (if any)?

^4.8.4

### What browser are you using?

Google Chrome

### Describe the Bug

I was following the [demo](https://rsuitejs.com/components/table/#virtualized) and noticed that it is way smoother than in my application. I removed everything from the app to look like the demo, but the issue is still there. Then I noticed that the roots of the app and the demo are created in different ways.

Long story short, a virtual table begins to stutter once it's hosted within React 18 root (like in my application):
```
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />)
```
![image](https://user-images.githubusercontent.com/8142668/195875970-b5e7cd8a-c813-4f03-bd6e-8db1e5801511.png)

And works perfectly under React 17 (like in the demo):
`ReactDOM.render(<App />, document.getElementById("root"));`
![image](https://user-images.githubusercontent.com/8142668/195876165-0b44a964-6d3b-457c-89f0-45c5d1364bd2.png)

### Expected Behavior

Virtual table should scroll smoothly using React 18

### To Reproduce

Here is [sandbox](https://codesandbox.io/s/virtual-table-behavior-z83r3j?file=/index.js)

1. Open index.js
2. Comment/keep only one creation of the root
3. Try to scroll the table

**Comment by simonguo** [comment]
Due to the asynchronous rendering mechanism of React 18, elements that directly manipulate the DOM cannot be rendered to the page in time.

https://github.com/rsuite/rsuite-table/pull/359
We are currently using `ReactDOM.flushSync` to force React to flush synchronously. Fluency is much better than before the fix, but there is still stuttering when scrolling fast. It will be improved as a suitable solution is found.

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite-table/pull/387
