### ISSUE TITLE
checkTree is not at all working with the data of around 10k values

### ISSUE THREAD

**Issue by code-x-sreekanth** [rsuite/rsuite#3217]
The CheckTree works fine if I pass the data around 100 values. But the problem is we need to show approximately 10,000 values in the list. it is failing to render when I am trying to render the CheckTree component with that huge data of around 10K values. I have tried virtualization as well. Is anyone facing the same issue?

**Comment by SevenOutman** [comment]
Hi @code-x-sreekanth, I noticed that you've already [opened a discussion](https://github.com/rsuite/rsuite/discussions/3216) around this topic, so I believe this issue is redundant and am going to close it.

If you do want to open an issue as bug report, feel free to reopen, and please follow the issue template to provide necessary info for us to reproduce and locate the problem.
