### ISSUE TITLE
InputPicker styles are less specific than Picker styles

### ISSUE THREAD

**Issue by ab-pm** [rsuite/rsuite#3328]
### What version of rsuite are you using?

5.28.3

### Describe the Bug

*rsuite/InputPicker/styles/index.less* defines 
```less
.rs-picker-input {
  …
  .rs-picker-toggle {
    …
    cursor: text;
  }
}
```
which is meant to override the `cursor: pointer` style that is defined on the `.rs-picker-default .rs-picker-toggle` selector. However, it comes after the latter in the generated .css file, so it does not actually apply the `cursor: text` to the element.
Unfortunately I cannot quite figure out where the `.rs-picker-default .rs-picker-toggle` selector comes from (I'm new to .less) but my guess is that this specificity issue is caused by the alphabetical import order in *rsuite/styles/index.less*. It should import the common/default styles first, the specific modules later?

### Expected Behavior

The `<InputPicker>` should have a text cursor.

**Comment by SevenOutman** [comment]
@ab-pm Thanks for raising this!

It could probably be caused by the order of the class declarations. But after inspecting the CSS overrides, I guess the `.rs-picker-default .rs-picker-toggle` here might be just redundant here as we already specified `cursor: pointer` for general picker toggles with `.rs-picker-toggle` class.

<img width="416" alt="image" src="https://github.com/rsuite/rsuite/assets/8225666/54d1a287-59c2-4a3f-b738-82710d623631">

I'll look into how we should fix this.
