### ISSUE TITLE
How do I change the inner placeholder

### ISSUE THREAD

**Issue by kernelguardian** [rsuite/rsuite#3359]
<img width="375" alt="Screenshot 2023-09-04 at 6 11 00 pm" src="https://github.com/rsuite/rsuite/assets/20723393/aaf2c78e-e910-42c3-a771-c72129fa5ec3">

I was trying out the Cascader Component. I have no idea on how to change the placeholder value for the inner search input.

https://rsuitejs.com/components/cascader/#props

**Comment by SevenOutman** [comment]
If you want to use built-in language presets you can follow the i18n guide https://rsuitejs.com/guide/i18n/

Otherwise, if you only wish to customize a single component instance, use `locale.searchPlaceholder` prop.

```jsx
<Cascader 
  data={data}
  locale={{ 
    searchPlaceholder: 'Custom placeholder'
  }} 
/>
```

<img width="282" alt="image" src="https://github.com/rsuite/rsuite/assets/8225666/10217185-ded0-40c9-aeba-64708be7bd16">

Ref: https://rsuitejs.com/guide/i18n/#pickers
