### ISSUE TITLE
RTL Support | Drawer Placement Problem

### ISSUE THREAD

**Issue by Anas-Abdelhadi** [rsuite/rsuite#727]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.11` |
| `rsuite` | `4.1.1` |

### What is the expected behavior?

In the Drawer component, the direction should be **automatically** flipped without having to touch the code.

Direction does not work as expected.

### What is the current behavior?
this.toggleDrawer('left')  opens the drawer from the **left**. 
changing to **RTL** should cause the same code to open the Drawer from the **right**

### What are the steps to reproduce?
create a drawer with default settings, or specify placement as left. change the **dir** of the page to **RTL** the drawer will behave exactly similar to **LTR** case

**Comment by MohammadYounes** [comment]
@simonguo The drawer component placement is fully CSS based. However, the current approach of combining both LTR/RTL styles is preventing it from operating correctly due to keyframes not being flipped (disabled [here](https://github.com/rsuite/rsuite/blob/216812af30a12dc7882470ab91039b5e64f98d12/src/styles/keyframes.less#L287-L351)).

To fix this, you have 2 options:

1. Allow the keyframes to be flipped and generate different classes 
```css
[dir=ltr] .left.slide-in {
   animation-name: slideInLeft-ltr
}

[dir=rtl] .left.slide-in {
    animation-name: slideInLeft-rtl
}
```

2. Reverse the placement in [script](https://github.com/rsuite/rsuite/blob/master/src/Drawer/Drawer.tsx#L27), which requires subscribing to `IntlContext` and swapping `left` with `right` and vice versa.

That being said,  The above options would not be required if you switch to generating a complete RTL stylesheet and the Drawer would work correctly out of the box. Moreover, you'll be able to utilize all of [rtlcss](https://rtlcss.com/) features as an added bonus.

Most likely, users will be viewing the app in either LTR or RTL language but not both, similar to light/dark themes. 

Will you be open to making the switch ?

**Comment by simonguo** [comment]
@MohammadYounes 
There is some doubt about whether `right` and `left` need to be reversed.
My idea is that if the two parameters `right` and `left` are already provided to the developer, then the developer can judge according to their own locale. After all, a website will normally have only one reading habit.

Of course, I am not quite sure how this problem is understood in your country. If you really need to reverse `right` and `left`, I prefer your second option.

**Comment by MohammadYounes** [comment]
> There is some doubt about whether right and left need to be reversed.

@simonguo There should be no doubt about this, since I should be able to build bi-lingual apps with one code base without worrying about controls placement. 

For example, See how the docs top level nav and sidebar are automatically mirrored to the opposite side to match the document flow.

![LTR-vs-RTL](https://user-images.githubusercontent.com/4712046/69051852-27b1b900-0a0e-11ea-9c82-16a40161cf6b.png)


> My idea is that if the two parameters right and left are already provided to the developer, then the developer can judge according to their own locale.

Having both directions available is great, But it's logically incorrect. 

**Incorrect**:

![Drawer LTR-vs-RTL](https://user-images.githubusercontent.com/4712046/69051929-5af44800-0a0e-11ea-8739-fac4f7a4113b.png)

**Correct**:

![Drawer2 LTR-vs-RTL](https://user-images.githubusercontent.com/4712046/69052044-a7d81e80-0a0e-11ea-8d5f-52b214e3f240.png)

In logical properties, wouldn't I just set the drawer placement to `Start` and it should follow the document direction ?

 * `Start` means `Left` in LTR 
 * `Start` means `Right` in RTL 


> Of course, I am not quite sure how this problem is understood in your country. If you really need to reverse right and left, I prefer your second option.

Why not the 3rd option (generating a complete RTL version)? which gives the following advantages:
 - Zero effort in mirroring CSS based components.
 - Smaller bundle size, the current combined CSS size is larger by **36%**. Which will be saved for apps that have one language direction.

**Comment by simonguo** [comment]
The following example expresses my opinion.

```html
<div style="direction: rtl;">1 2 3 4 5 6</div>
<div style="text-align:left; direction:rtl;">1 2 3 4 5 6</div>
<div style="text-align:right;">1 2 3 4 5 6</div>
```
![right-left](https://user-images.githubusercontent.com/1203827/69059096-d4f8f100-0a4f-11ea-9f02-3f2cb05b392c.png)
```html
<div style="direction: rtl;">1 2 3 4 5 6</div>
<div style="text-align:start; direction:rtl;">1 2 3 4 5 6</div>
<div style="text-align:end;">1 2 3 4 5 6</div>
```
![srart-end](https://user-images.githubusercontent.com/1203827/69059125-e3470d00-0a4f-11ea-9afc-4c7a0434c0ca.png)

`right` and `left` represent a specific direction, and if directly reversed, it may be semantically ambiguous. This is the reason why I am confused. Do you understand?

If the API is designed to be `right` and `left`, I might prefer to let the developer set it up. Just like `text-align:left/right`.

I am more inclined to design the API as `start` and `end`, but I also need to deal with compatibility issues, which is also my entanglement.

**Comment by MohammadYounes** [comment]
@simonguo In this case the developer will have a tremendous headache of flipping UI controls based on language rather than delegating it to the UI framework being used.

You need to think of bi-lingual apps,  my source code for both LTR and RTL should be the same.


**Setting the document direction will be the only required change**.

For example:

* LTR
```css
<section dir="ltr">
  <div>Default: 1 2 3 4 5 6</div>
  <div style="text-align:start;">Start: 1 2 3 4 5 6</div>
  <div style="text-align:end;">End: 1 2 3 4 5 6</div>
</section>
```

* RTL
```css
<section dir="rtl">
  <div>Default: 1 2 3 4 5 6</div>
  <div style="text-align:start;">Start: 1 2 3 4 5 6</div>
  <div style="text-align:end;">End: 1 2 3 4 5 6</div>
</section>
```

Which produces:

![image](https://user-images.githubusercontent.com/4712046/69063265-dd880200-0a24-11ea-946d-27cd2f2c9c94.png)


The API should be based on one language direction, with the other direction being an exact mirror. 

Logical properties uses the terms Start/End to avoid this confusion, while at the same time follows document direction translating Start to Left in LTR and to Right in RTL.

**Comment by simonguo** [comment]
Well, what you said makes sense.
In bilingual apps, it is indeed inconvenient for developers to do custom judgments.

Thank you, we will be improving the components to support RTL features, and you are welcome to participate.

**Comment by MohammadYounes** [comment]
Great! Thanks for the invitation.
